### ISSUE TITLE
Script to get stop times from Miccolis timetables: double pole numbers parsing error

### ISSUE THREAD

**Issue by mstn** [mapourtransit/gtfs-maker#3]
For some reason 104-105 is parsed as 104 -,105

104 -,105 P.ZZA MATTEOTTI,7:02,
106 -,107 VIA MORO,7:03,Ist. Commerciale

**Comment by elf-pavlik** [comment]
Please continue in Miccolis specific repo: https://github.com/unmonastery/miccolis-parser/issues/1
