### ISSUE TITLE
How to treat timetable variations on school days?

### ISSUE THREAD

**Issue by albertocottica** [mapourtransit/gtfs-maker#7]
Maybe you guys have solved this already... I am working on https://github.com/unmonastery/GtfsMaker/blob/stoptimes/miccolis/calendar/by_line.txt, and it turns out that line 11 has variations specific for school days. How to treat them?

**Comment by elf-pavlik** [comment]
Please continue in Matera specific repo: https://github.com/unmonastery/matera-gtfs/issues/7
