### ISSUE TITLE
New timetable CSV under construction

### ISSUE THREAD

**Issue by albertocottica** [mapourtransit/gtfs-maker#8]
https://docs.google.com/spreadsheets/d/1zV_WcNrjuX9ErcmBcHVU9-CW57Qwm2JpNTqOOxjic3I/edit#gid=0

So far I have input lines 2 and 3, on top of line 1 already input by Marco.

**Comment by elf-pavlik** [comment]
@albertocottica @mstn can you take another look at line 14 and 15?

**Comment by albertocottica** [comment]
We discussed this with @mstn. The decision was that he needs to think about an improved procedure for me to input the many exceptions to the rules: first and last trips, schoolday variations etc. They might go directly in the GTFS file. Once he has decided, I can enrich the data files he chooses to work with.

**Comment by elf-pavlik** [comment]
Please continue in Matera specific repo: https://github.com/unmonastery/matera-gtfs/issues/7
