### ISSUE TITLE
Substitute "Linea 8" with "Linea Via Fermi - Piazza Sant'Agnese"

### ISSUE THREAD

**Issue by piersoft** [mapourtransit/gtfs-maker#9]
please substitue every lines (https://github.com/unmonastery/matera-gtfs/blob/master/routes.txt) with real name from start and stop places.

http://www.miccolis-spa.it/lecce-napoli-da-scoprire/matera on the right, there are every pdf (sigh) routes

**Comment by elf-pavlik** [comment]
Please continue in Matera specific repo: https://github.com/unmonastery/matera-gtfs/issues/5
